CREATE PROCEDURE [silver.FNC].SP_MAPPING_SURROGATE_KEYS_DIMS
AS
BEGIN

    SET XACT_ABORT ON;
    SET NOCOUNT OFF;

    DECLARE @Timestamp DATETIME = GETUTCDATE();

    INSERT INTO [silver.FNC].MAPPING_SURROGATE_KEYS_DIMS  WITH (ROWLOCK) (UQ_KEY, UQ_KEY_HASH, DIM_ID, DIMENSION, ROW_CREATED_AT)
    SELECT 
        dm.UQ_KEY,
        dm.UQ_KEY_HASH,
        NEXT VALUE FOR [silver.FNC].SEQ_ACCOUNT_DIM AS DIM_ID, 
        'ACCOUNT_DIM' AS DIMENSION,
        @Timestamp
    FROM [silver.FNC].VW_ACCOUNT_DIM AS dm
        LEFT JOIN [silver.FNC].MAPPING_SURROGATE_KEYS_DIMS as ks WITH (ROWLOCK)
            ON ks.UQ_KEY_HASH = dm.UQ_KEY_HASH
            AND ks.DIMENSION = 'ACCOUNT_DIM'
    WHERE ks.UQ_KEY_HASH IS NULL;

    INSERT INTO [silver.FNC].MAPPING_SURROGATE_KEYS_DIMS WITH (ROWLOCK) (UQ_KEY, UQ_KEY_HASH, DIM_ID, DIMENSION, ROW_CREATED_AT)
    SELECT 
        dm.UQ_KEY,
        dm.UQ_KEY_HASH,
        NEXT VALUE FOR [silver.FNC].SEQ_DEPARTMENT_DIM AS DIM_ID, 
        'DEPARTMENT_DIM' AS DIMENSION,
        @Timestamp
    FROM [silver.FNC].VW_DEPARTMENT_DIM AS dm
        LEFT JOIN [silver.FNC].MAPPING_SURROGATE_KEYS_DIMS as ks WITH (ROWLOCK)
            ON ks.UQ_KEY_HASH = dm.UQ_KEY_HASH
            AND ks.DIMENSION = 'DEPARTMENT_DIM'
    WHERE ks.UQ_KEY_HASH IS NULL;

END;