CREATE PROCEDURE [silver.FNC].SP_RUN
AS
BEGIN

    SET XACT_ABORT ON;
    SET NOCOUNT OFF;
    
    EXEC [silver.FNC].SP_MAPPING_SURROGATE_KEYS_DIMS;
    EXEC [silver.FNC].SP_ACCOUNT_DIM;
    EXEC [silver.FNC].SP_DEPARTMENT_DIM;
    EXEC [silver.FNC].SP_TRANSACTION_TITLE_DIM;
    EXEC [silver.FNC].SP_TRANSACTION_FACT;
    EXEC [silver.FNC].SP_BUDGET_FACT;

END;