CREATE TABLE [gold.NCCM].[PARTICIPANTS_BRIDGE](
    [CONTACT_DIM_ID] [int] NOT NULL,
    [PROGRAM_ENGAGEMENT_DIM_ID] [int] NOT NULL,
    [IS_DELETED] [int] NULL,
    [ROW_CALENDAR_DATE] [date] NOT NULL,
    [ROW_CREATED_AT] [datetime] NOT NULL,
    [ROW_UPDATED_AT] [datetime] NOT NULL
)