CREATE TABLE [gold.NCCM].[PROGRAM_FACT](
    [ORIGINAL_SYSTEM_CREATED_DATE] [date] NULL,
    [PROGRAM_NAME] [varchar](255) NULL,
    [CONTACT_DIM_ID] [int] NULL,
    [CLAIM_DIM_ID] [int] NULL,
    [PROGRAMENGAGEMENT_DIM_ID] [int] NOT NULL
)