CREATE PROCEDURE [silver.NCCM].SP_MAPPING_SURROGATE_KEYS_DIMS
AS
BEGIN

    SET XACT_ABORT ON;
    SET NOCOUNT OFF;

    INSERT INTO [silver.NCCM].MAPPING_SURROGATE_KEYS_DIMS  WITH (ROWLOCK) (UQ_KEY, UQ_KEY_HASH, DIM_ID, DIMENSION)
    SELECT 
        dm.UQ_KEY,
        dm.UQ_KEY_HASH,
        NEXT VALUE FOR [silver.NCCM].SEQ_CLAIMS_DIM AS DIM_ID, 
        'CLAIMS_DIM' AS DIMENSION
    FROM [silver.NCCM].VW_AS_CLAIMS_DIM AS dm
        LEFT JOIN [silver.NCCM].MAPPING_SURROGATE_KEYS_DIMS as ks WITH (ROWLOCK)
            ON ks.UQ_KEY_HASH = dm.UQ_KEY_HASH
            AND ks.DIMENSION = 'CLAIMS_DIM'
    WHERE ks.UQ_KEY_HASH IS NULL;

    INSERT INTO [silver.NCCM].MAPPING_SURROGATE_KEYS_DIMS WITH (ROWLOCK) (UQ_KEY, UQ_KEY_HASH, DIM_ID, DIMENSION)
    SELECT 
        dm.UQ_KEY,
        dm.UQ_KEY_HASH,
        NEXT VALUE FOR [silver.NCCM].SEQ_CONTACTS_DIM AS DIM_ID, 
        'CONTACTS_DIM' AS DIMENSION
    FROM [silver.NCCM].VW_CONTACTS_DIM AS dm
        LEFT JOIN [silver.NCCM].MAPPING_SURROGATE_KEYS_DIMS as ks WITH (ROWLOCK)
            ON ks.UQ_KEY_HASH = dm.UQ_KEY_HASH
            AND ks.DIMENSION = 'CONTACTS_DIM'
    WHERE ks.UQ_KEY_HASH IS NULL;

    INSERT INTO [silver.NCCM].MAPPING_SURROGATE_KEYS_DIMS WITH (ROWLOCK) (UQ_KEY, UQ_KEY_HASH, DIM_ID, DIMENSION)
    SELECT 
        dm.UQ_KEY,
        dm.UQ_KEY_HASH,
        NEXT VALUE FOR [silver.NCCM].SEQ_JOB_ORDERS_DIM AS DIM_ID, 
        'JOB_ORDERS_DIM' AS DIMENSION
    FROM [silver.NCCM].VW_JOB_ORDERS_DIM AS dm
        LEFT JOIN [silver.NCCM].MAPPING_SURROGATE_KEYS_DIMS as ks WITH (ROWLOCK)
            ON ks.UQ_KEY_HASH = dm.UQ_KEY_HASH
            AND ks.DIMENSION = 'JOB_ORDERS_DIM'
    WHERE ks.UQ_KEY_HASH IS NULL;

    INSERT INTO [silver.NCCM].MAPPING_SURROGATE_KEYS_DIMS (UQ_KEY, UQ_KEY_HASH, DIM_ID, DIMENSION)
    SELECT 
        dm.UQ_KEY,
        dm.UQ_KEY_HASH,
        NEXT VALUE FOR [silver.NCCM].SEQ_OUTCOME_DIM AS DIM_ID, 
        'OUTCOME_DIM' AS DIMENSION
    FROM [silver.NCCM].VW_OUTCOME_DIM AS dm
        LEFT JOIN [silver.NCCM].MAPPING_SURROGATE_KEYS_DIMS as ks
            ON ks.UQ_KEY_HASH = dm.UQ_KEY_HASH
            AND ks.DIMENSION = 'OUTCOME_DIM'
    WHERE ks.UQ_KEY_HASH IS NULL;

    INSERT INTO [silver.NCCM].MAPPING_SURROGATE_KEYS_DIMS WITH (ROWLOCK) (UQ_KEY, UQ_KEY_HASH, DIM_ID, DIMENSION)
    SELECT 
        dm.UQ_KEY,
        dm.UQ_KEY_HASH,
        NEXT VALUE FOR [silver.NCCM].SEQ_PLACEMENT_DIM AS DIM_ID, 
        'PLACEMENT_DIM' AS DIMENSION
    FROM [silver.NCCM].VW_PLACEMENT_DIM AS dm
        LEFT JOIN [silver.NCCM].MAPPING_SURROGATE_KEYS_DIMS as ks WITH (ROWLOCK)
            ON ks.UQ_KEY_HASH = dm.UQ_KEY_HASH
            AND ks.DIMENSION = 'PLACEMENT_DIM'
    WHERE ks.UQ_KEY_HASH IS NULL;
    
    INSERT INTO [silver.NCCM].MAPPING_SURROGATE_KEYS_DIMS WITH (ROWLOCK) (UQ_KEY, UQ_KEY_HASH, DIM_ID, DIMENSION)
    SELECT 
        dm.UQ_KEY,
        dm.UQ_KEY_HASH,
        NEXT VALUE FOR [silver.NCCM].SEQ_PROGRAMENGAGEMENT_DIM AS DIM_ID, 
        'PROGRAMENGAGEMENT_DIM' AS DIMENSION
    FROM [silver.NCCM].VW_PROGRAMENGAGEMENT_DIM AS dm
        LEFT JOIN [silver.NCCM].MAPPING_SURROGATE_KEYS_DIMS as ks WITH (ROWLOCK)
            ON ks.UQ_KEY_HASH = dm.UQ_KEY_HASH
            AND ks.DIMENSION = 'PROGRAMENGAGEMENT_DIM'
    WHERE ks.UQ_KEY_HASH IS NULL;

END;