CREATE PROCEDURE [raw.NCCM].FFS_CLEAN_TABLES
AS
BEGIN

    DBCC CHECKIDENT ('[raw.NCCM].FFS_CONTACT', RESEED, 1);
    DBCC CHECKIDENT ('[raw.NCCM].FFS_PMDM__PROGRAMENGAGEMENT__C', RESEED, 1);

    TRUNCATE TABLE [raw.NCCM].FFS_CONTACT;
    TRUNCATE TABLE [raw.NCCM].FFS_PMDM__PROGRAMENGAGEMENT__C;

END;