CREATE TABLE [bronze.NCCM].AS_CLAIMS (
    -- PK
    [ID] VARCHAR(18) NOT NULL,

    -- Attributes
    [AS_APPROVED_AMOUNT__C] INT NULL,
    [AS_CLAIM_AMOUNT__C] INT NULL,
    [AS_CLAIM_ID__C] VARCHAR(18) NULL,
    [AS_CLAIM_RATE_TYPE__C] VARCHAR(255) NULL,
    [AS_GST_AMOUNT__C] INT NULL,
    [AS_JOBSEEKER_ID__C] VARCHAR(18) NULL,
    [AS_STATUS_DATE__C] DATE NULL,
    [AS_STATUS__C] VARCHAR(255) NULL,
    [NAME] NVARCHAR(1024) NULL,
    [OUTCOME_TYPE__C] VARCHAR(255) NULL,
    [SITE_CODE__C] VARCHAR(255) NULL,
    [ISDELETED] INT NOT NULL,

    -- Hash
    [ROW_HASH_SUM] VARCHAR(32) NOT NULL,

    -- Temporal
    [RowVersion] ROWVERSION NOT NULL,
    [ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo]),

    CONSTRAINT PK_AS_CLAIMS PRIMARY KEY CLUSTERED ([Id])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [bronze.NCCM].AS_CLAIMS_HISTORY));