CREATE TABLE [bronze.NCCM].CASE_CLIENT (
    -- PK
    [ID] VARCHAR(18) NOT NULL,

    -- Attributes
    [CLIENT_CONTACT__C] VARCHAR(18) NULL,
    [ISDELETED] INT NOT NULL,

    -- Hash
    [RowHashSum] VARCHAR(32) NOT NULL,

    -- Temporal
    [RowVersion] ROWVERSION NOT NULL,
    [ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo]),

    CONSTRAINT PK_CASE_CLIENT PRIMARY KEY CLUSTERED ([Id])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [bronze.NCCM].CASE_CLIENT_HISTORY));
