CREATE TABLE [bronze.NCCM].CONTACTS (
    -- PK
    [ID] VARCHAR(18) NOT NULL,

    -- Attributes
    [LASTNAME] NVARCHAR(1024) NULL,
    [FIRSTNAME] NVARCHAR(1024) NULL,
    [BIRTHDATE] DATE NULL,
    [GENDER__C] VARCHAR(255) NULL,
    [JOBSEEKERID__C] VARCHAR(18) NULL,
    [ACCOUNTID] VARCHAR(18) NULL,
    [ISDELETED] INT NOT NULL,

    -- Hash
    [ROW_HASH_SUM] VARCHAR(32) NOT NULL,

    -- Temporal
    [RowVersion] ROWVERSION NOT NULL,
    [ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo]),

    CONSTRAINT PK_CONTACTS PRIMARY KEY CLUSTERED ([Id])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [bronze.NCCM].CONTACTS_HISTORY));
