CREATE TABLE [bronze.NCCM].CONTACTS (
    -- PK
    [Id] VARCHAR(18) NOT NULL,

    -- Attributes
    [LastName] NVARCHAR(1024) NULL,
    [FirstName] NVARCHAR(1024) NULL,
    [Birthdate] DATE NULL,
    [Gender__c] VARCHAR(255) NULL,
    [JobSeekerId__c] VARCHAR(18) NULL,
    [AccountId] VARCHAR(18) NULL,
    [IsDeleted] INT NOT NULL,

[DFV_ABUSE_COERCIVE_CONTROL__C] NVARCHAR(MAX) NULL,
    [DFV_ABUSE_CULTURAL_SPIRITUAL__C] NVARCHAR(MAX) NULL,
    [DFV_ABUSE_DOMESTIC_SERVITUDE__C] NVARCHAR(MAX) NULL,
    [DFV_ABUSE_DOWRY__C] NVARCHAR(MAX) NULL,
    [DFV_ABUSE_EMOTIONAL_PSYCHOLOGICAL__C] NVARCHAR(MAX) NULL,
    [DFV_ABUSE_FINANCIAL__C] NVARCHAR(MAX) NULL,
    [DFV_ABUSE_FORCED_MARRIAGE__C] NVARCHAR(MAX) NULL,
    [DFV_ABUSE_HARRASSMENT_STALKING__C] NVARCHAR(MAX) NULL,
    [DFV_ABUSE_IMMIGRATION_FACILITATED__C] NVARCHAR(MAX) NULL,
    [DFV_ABUSE_MULTIPERPETRATOR__C] NVARCHAR(MAX) NULL,
    [DFV_ABUSE_PHYSICAL__C] NVARCHAR(MAX) NULL,
    [DFV_ABUSE_REPRODUCTIVE__C] NVARCHAR(MAX) NULL,
    [DFV_ABUSE_SEXUAL__C] NVARCHAR(MAX) NULL,
    [DFV_ABUSE_STRANGULATION__C] NVARCHAR(MAX) NULL,
    [DFV_ABUSE_SYSTEMS__C] NVARCHAR(MAX) NULL,
    [DFV_ABUSE_TECHNOLOGY_FACILITATED__C] NVARCHAR(MAX) NULL,
    [DFV_ABUSE_VERBAL__C] NVARCHAR(MAX) NULL,
    [DFV_BARRIER_TO_DISCLOSURE_CULTURAL__C] NVARCHAR(MAX) NULL,
    [DFV_BARRIER_TO_DISCLOSURE_LANGUAGE__C] NVARCHAR(MAX) NULL,
    [DFV_BARRIER_TO_DISCLOSURE_MISIDENTIFY__C] NVARCHAR(MAX) NULL,
    [DFV_BARRIER_TO_DISCLOSURE_SYSTEM__C] NVARCHAR(MAX) NULL,
    [DFV_CASE_CONFERENCE_DATE__C] NVARCHAR(MAX) NULL,
    [DFV_CHILDREN_UNDER_18__C] NVARCHAR(MAX) NULL,
        [DISABILITY_TYPE__C] NVARCHAR(MAX) NULL,
    [EDUCATION_LEVEL__C] NVARCHAR(MAX) NULL,
    [INTERPRETER_LANGUAGE__C] NVARCHAR(MAX) NULL,
    [MENTAL_ILLNESS_FLAG__C] NVARCHAR(MAX) NULL,
    [VULNERABLE_YOUTH__C] NVARCHAR(MAX) NULL,
    [VULNERABLE_YOUTH_STUDENT__C] NVARCHAR(MAX) NULL,
    
    -- Hash
    [RowHashSum] VARCHAR(32) NOT NULL,

    -- Temporal
    [RowVersion] ROWVERSION NOT NULL,
    [ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo]),

    CONSTRAINT PK_CONTACTS PRIMARY KEY CLUSTERED ([Id])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [bronze.NCCM].CONTACTS_HISTORY));
