CREATE TABLE [bronze.NCCM].JOB_ORDERS (
    -- PK
    [ID] VARCHAR(18) NOT NULL,

    -- Attributes
    [HOST_ORGANISATION] VARCHAR(18) NULL,
    [JOB_ORDER_TYPE] VARCHAR(255) NULL,
    [JOB_TITLE] NVARCHAR(1024) NULL,
    [JOB_TYPE] NVARCHAR(1024) NULL,
    [ISDELETED] INT NOT NULL,

    -- Hash
    [RowHashSum] VARCHAR(32) NOT NULL,

    -- Temporal
    [RowVersion] ROWVERSION NOT NULL,
    [ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo]),

    CONSTRAINT PK_JOB_ORDERS PRIMARY KEY CLUSTERED ([Id])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [bronze.NCCM].JOB_ORDERS_HISTORY));
