CREATE TABLE [bronze.NCCM].OUTCOME (
    -- PK
    [ID] VARCHAR(18) NOT NULL,

    -- Attributes
    [WRD_PHASE__C] VARCHAR(1024) NULL,
    [RECORD_TYPE_NAME__C] VARCHAR(1024) NULL,
    [ISDELETED] INT NOT NULL,

    -- Hash
    [RowHashSum] VARCHAR(32) NOT NULL,

    -- Temporal
    [RowVersion] ROWVERSION NOT NULL,
    [ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo]),

    CONSTRAINT PK_OUTCOME PRIMARY KEY CLUSTERED ([Id])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [bronze.NCCM].OUTCOME_HISTORY));
