CREATE TABLE [bronze.NCCM].PARTICIPANTS (
    -- PK
    [ID] VARCHAR(18) NOT NULL,
    
    -- Attributes
    [CONTACT__C] VARCHAR(18) NULL,
    [PROGRAM_ENGAGEMENT__C] VARCHAR(18) NULL,
    [ISDELETED] INT NOT NULL,

    -- Hash
    [ROW_HASH_SUM] VARCHAR(32) NOT NULL,

    -- Temporal
    [RowVersion] ROWVERSION NOT NULL,
    [ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo]),

    CONSTRAINT PK_PARTICIPANTS PRIMARY KEY CLUSTERED ([Id])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [bronze.NCCM].PARTICIPANTS_HISTORY));
