CREATE TABLE [bronze.NCCM].PROGRAMENGAGEMENT (
    -- PK
    [Id] VARCHAR(18) NOT NULL,

    -- Attributes
    [AGE_OF_YOUNGEST_CHILD__C] INT NULL,
    [CALD__C] VARCHAR(255) NULL,
    [COMMENCEMENT_OF_SERVICING_DATE__C] DATE NULL,
    [PMDM__CONTACT__C] VARCHAR(18) NULL,
    [CONTRACT_REFERENCE_ID__C] VARCHAR(18) NULL,
    [CONTRACT_REFERRAL_START_DATE__C] DATE NULL,
    [CONTRACT_REFERRAL_STATUS__C] VARCHAR(255) NULL,
    [CRN__C] VARCHAR(255) NULL,
    [DES_PROGRAM_TYPE_CODE__C] VARCHAR(255) NULL,
    [ECM_CASE_ID__C] VARCHAR(18) NULL,
    [EMPLOYMENT_BENCHMARK__C] VARCHAR(1024) NULL,
    [ESAT_JCA_ASSESSMENT_DATE__C] DATE NULL,
    [EXIT_DATE__C] DATE NULL,
    [FUNDING_LEVEL__C] VARCHAR(255) NULL,
    [INDIGENOUS_INDICATOR__C] VARCHAR(255) NULL,
    [JOB_PLAN_STATUS__C] VARCHAR(255) NULL,
    [JSCI_ASSESSMENT_DATE__C] DATE NULL,
    [JSCI_STATUS__C] VARCHAR(255) NULL,
    [LATEST_RESUME_DATE__C] DATE NULL,
    [LINKED_ACTIVITY__C] VARCHAR(1024) NULL,
    [MATURE_AGE__C] INT NULL,
    [NEIS_FLAG__C] VARCHAR(255) NULL,
    [NEXT_APPOINTMENT_DATE__C] DATE NULL,
    [NEXT_SERVICE_DELIVERY__C] VARCHAR(1024) NULL,
    [ORIGINAL_COMMENCEMENT_DATE__C] DATE NULL,
    [OTHER_PERSONAL_ISSUES_BARRIERS__C] VARCHAR(1024) NULL,
    [OWNERID__C] VARCHAR(18) NULL,
    [PARTICIPATION_PLAN_STATUS__C] VARCHAR(255) NULL,
    [PERIOD_OF_SERVICE__C] VARCHAR(255) NULL,
    [POI_CHECKED__C] VARCHAR(255) NULL,
    [PRINCIPAL_PARENT_CARER__C] VARCHAR(255) NULL,
    [PROGRAM_NAME__C] VARCHAR(255) NULL,
    [REFERRAL_DATE__C] DATE NULL,
    [REFERRAL_PHASE_CODE__C] VARCHAR(255) NULL,
    [REFERRAL_STATUS_CODE__C] VARCHAR(255) NULL,
    [REFUGEE_HUMANITARIAN_VISA__C] VARCHAR(255) NULL,
    [SERVICING_PLACEMENT_STATUS__C] VARCHAR(255) NULL,
    [SITE_CODE__C] VARCHAR(255) NULL,
    [SSI_SITE__C] VARCHAR(255) NULL,
    [SUSPENSION_REASON_DESCRIPTION__C] VARCHAR(255) NULL,
    [THINK_TIME_DAYS__C] VARCHAR(255) NULL,
    [THINK_TIME_ELECTED__C] VARCHAR(255) NULL,
    [TRAFFIC_LIGHT__C] VARCHAR(255) NULL,
    [IsDeleted] INT NOT NULL,

    -- Hash
    [RowHashSum] VARCHAR(32) NOT NULL,

    -- Temporal
    [RowVersion] ROWVERSION NOT NULL,
    [ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo]),

    CONSTRAINT PK_PROGRAMENGAGEMENT PRIMARY KEY CLUSTERED ([Id])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [bronze.NCCM].PROGRAMENGAGEMENT_HISTORY));
