CREATE TABLE [silver.NCCM].PARTICIPANTS_BRIDGE (
    [PARTICIPANT_BRIDGE_ID] INT IDENTITY(1, 1) NOT NULL,
    [ROW_HASH_SUM] BINARY(16) NOT NULL,

    [CONTACT_DIM_ID] INT NOT NULL,
    [PROGRAM_ENGAGEMENT_DIM_ID] INT NOT NULL,
    [IS_DELETED] INT NULL,

    [ROW_CALENDAR_DATE] DATE NOT NULL,
    [ROW_CREATED_AT] DATETIME NOT NULL,
    [ROW_UPDATED_AT] DATETIME NOT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,

    CONSTRAINT [PK_PARTICIPANTS_BRIDGE] PRIMARY KEY ([PARTICIPANT_BRIDGE_ID])
)
