CREATE TABLE [silver.NCCM].PLACEMENT_DIM (
    [PLACEMENT_DIM_ID] INT NOT NULL,
    [NK_STRING] NVARCHAR(MAX) NOT NULL,
    [ROW_HASH_SUM] BINARY(16) NOT NULL,

    [ARCHIVAL] BIT NOT NULL CONSTRAINT DF_PLACEMENT_DIM_ARCHIVAL DEFAULT(0),

    -- nullable
    [PLACEMENT_ID] VARCHAR(18) NULL,
    [ANCHOR_DATE] DATE NULL,
    [CONTACT_DIM_ID] INT NULL,
    [END_DATE] DATE NULL,
    [INTERVIEW_DATE] DATE NULL,
    [PLACED_DATE] DATE NULL,
    [PLACEMENT_TYPE] VARCHAR(255) NULL,
    [REFERRED_TO_EMPLOYER_DATE] DATE NULL,
    [START_DATE] DATE NULL,
    [STATUS] VARCHAR(255) NULL,
    [VACANCY_ID] VARCHAR(255) NULL,
    [IS_DELETED] INT NULL,

    [ROW_CALENDAR_DATE] DATE NOT NULL,
    [ROW_CREATED_AT] DATETIME NULL,
    [ROW_UPDATED_AT] DATETIME NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,

    [VALID_FROM] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    [VALID_TO] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME ([VALID_FROM], [VALID_TO]),

    CONSTRAINT [PK_PLACEMENT_DIM] PRIMARY KEY (PLACEMENT_DIM_ID)
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [silver.NCCM].PLACEMENT_DIM_HISTORY));