CREATE TABLE [silver.NCCM].PNX_HISTORY (
    [CLIENT] VARCHAR(18) NOT NULL,
    [UQ_KEY_HASH] BINARY(16) NOT NULL,
    [CONTRACT_REFERRAL_STATUS] VARCHAR(255) NULL,
    [SERVICING_PLACEMENT_STATUS] VARCHAR(255) NULL,
    [SITE_CODE] VARCHAR(255) NULL,
    [COMMENCEMENT_OF_SERVICING_DATE] DATE NULL,
    [ROW_IS_CURRENT] BIT NOT NULL,
    [ROW_IS_CURRENT_FOR_THE_DAY] BIT NOT NULL,
    [ROW_EFFECTIVE_DATE_TIME] DATETIME NOT NULL,
    [ROW_CALENDAR_DATE] DATE NOT NULL,
    [ROW_END_DATE_TIME] DATETIME NULL,
    [ROW_REASON_FOR_CHANGE] NVARCHAR(1024) NULL,
    [ROW_HASH_SUM] BINARY(16) NOT NULL,
    CONSTRAINT [PK_PNX_HISTORY] PRIMARY KEY (CLIENT, ROW_EFFECTIVE_DATE_TIME)
)