CREATE VIEW [silver.NCCM].VW_PNX_HISTORY
AS
    SELECT 
        UPPER(stm.CLIENT) AS UQ_KEY,
        HASHBYTES('MD5', UPPER(stm.CLIENT)) AS UQ_KEY_HASH,
        HASHBYTES('MD5', CONCAT(
            stm.COMMENCEMENT_OF_SERVICING_DATE,
            stm.CONTRACT_REFERRAL_STATUS,
            stm.SITE_CODE,
            stm.SERVICING_PLACEMENT_STATUS
        )) AS ROW_HASH_SUM,
        stm.*
    FROM (
        SELECT
            tbl.ID AS CLIENT,
            tbl.COMMENCEMENT_OF_SERVICING_DATE__C AS COMMENCEMENT_OF_SERVICING_DATE,
            tbl.CONTRACT_REFERRAL_STATUS__C AS CONTRACT_REFERRAL_STATUS,
            tbl.SITE_CODE__C AS SITE_CODE,
            tbl.SERVICING_PLACEMENT_STATUS__C AS SERVICING_PLACEMENT_STATUS
        FROM [bronze.NCCM].PROGRAMENGAGEMENT AS tbl
    ) AS stm;
