CREATE TABLE [raw.NCCM].FFS_PMDM__PROGRAMENGAGEMENT__C (
    [ID] BIGINT IDENTITY(1,1) NOT NULL,
    [RECORD] NVARCHAR(MAX) NULL,
    [FILE_NAME] NVARCHAR(2000) NOT NULL,
    [RUN_ID] UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_FFS_PMDM__PROGRAMENGAGEMENT__C_RUN_ID DEFAULT('00000000-0000-0000-0000-000000000001'),
    [CREATED_AT_UTC] DATETIME CONSTRAINT DF_FFS_PMDM__PROGRAMENGAGEMENT__C_CREATED_AT_UTC DEFAULT(GETUTCDATE())
)