CREATE TABLE [gold.FNC].DEPARTMENT_DIM (
    [DEPARTMENT_DIM_ID] INT NOT NULL,
    [ROW_HASH_SUM] BINARY(16) NOT NULL,

    [ARCHIVAL] BIT NOT NULL CONSTRAINT DF_DEPARTMENT_DIM_ARCHIVAL DEFAULT(0),

    -- nullable
    [TITLE] NVARCHAR(255) NULL,
    [LEVEL] INT NULL,
    [DEPARTMENT_ID] NVARCHAR(255) NULL,
    [PARENT_ID] NVARCHAR(255) NULL,
    [PARENT_NAME] NVARCHAR(2000) NULL,
    [SUPERVISOR_NAME] NVARCHAR(255) NULL,
    [PATH] VARCHAR(1014) NULL,

    -- not nullable
    [IS_DELETED] INT NOT NULL,

    [ROW_CREATED_AT] DATETIME NOT NULL,
    [ROW_UPDATED_AT] DATETIME NOT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,

    [VALID_FROM] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    [VALID_TO] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME ([VALID_FROM], [VALID_TO]),

    CONSTRAINT [PK_DEPARTMENT_DIM] PRIMARY KEY (DEPARTMENT_DIM_ID)
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [gold.FNC].DEPARTMENT_DIM_HISTORY));