CREATE TABLE [gold.FNC].TRANSACTION_FACT (
    [TRANSACTION_FACT_ID] INT IDENTITY(1, 1) NOT NULL,

    -- nullable
    [DEPARTMENT_DIM_ID] INT NULL,
    [ACCOUNT_DIM_ID] INT NULL,
    [BATCH_DATE] DATE NULL,
    [AMOUNT] DECIMAL(28, 6) NULL,

    -- not nullable
    [IS_DELETED] INT NOT NULL,

    [ROW_CREATED_AT] DATETIME NOT NULL,
    [ROW_UPDATED_AT] DATETIME NOT NULL

    CONSTRAINT [PK_TRANSACTION_FACT] PRIMARY KEY (TRANSACTION_FACT_ID)
);