CREATE TABLE [silver.NCCM].CLAIMS_DIM (
    [CLAIM_DIM_ID] INT NOT NULL,
    [NK_STRING] NVARCHAR(MAX) NOT NULL,
    [ROW_HASH_SUM] BINARY(16) NOT NULL,

    [ARCHIVAL] BIT NOT NULL CONSTRAINT DF_CLAIMS_DIM_ARCHIVAL DEFAULT(0),

    -- nullable
    [APPROVED_AMOUNT] INT NULL,
    [CLAIM_AMOUNT] INT NULL,
    [AS_CLAIM_ID] VARCHAR(18) NULL,
    [CLAIM_RATE_TYPE] VARCHAR(255) NULL,
    [GST_AMOUNT] INT NULL,
    [JOB_SEEKER_ID] VARCHAR(18) NULL,
    [STATUS_DATE] DATE NULL,
    [STATUS] VARCHAR(255) NULL,
    [NAME] NVARCHAR(1024) NULL,
    [OUTCOME_TYPE] VARCHAR(255) NULL,
    [SITE_CODE] VARCHAR(255) NULL,
    [IS_DELETED] INT NOT NULL,

    [ROW_CALENDAR_DATE] DATE NOT NULL,
    [ROW_CREATED_AT] DATETIME NOT NULL,
    [ROW_UPDATED_AT] DATETIME NOT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,

    CONSTRAINT [PK_CLAIMS_DIM] PRIMARY KEY (CLAIM_DIM_ID)
)
