CREATE TABLE [silver.NCCM].OUTCOME_DIM (
    [OUTCOME_DIM_ID] INT NOT NULL,
    [NK_STRING] NVARCHAR(MAX) NOT NULL,
    [ROW_HASH_SUM] BINARY(16) NOT NULL,

    [ARCHIVAL] BIT NOT NULL CONSTRAINT DF_OUTCOME_DIM_ARCHIVAL DEFAULT(0),

    -- nullable
    [OUTCOME_ID] VARCHAR(18) NULL,
    [CLIENT_CASE_ID] VARCHAR(18) NULL,
    [CONTACT_DIM_ID] INT NULL,
    [WRD_PHASE] VARCHAR(1024) NULL,
    [RECORD_TYPE_NAME] VARCHAR(1024) NULL,
    [IS_DELETED] INT NULL,

    [ROW_CALENDAR_DATE] DATE NOT NULL,
    [ROW_CREATED_AT] DATETIME NULL,
    [ROW_UPDATED_AT] DATETIME NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,

    CONSTRAINT [PK_OUTCOME_DIM] PRIMARY KEY (OUTCOME_DIM_ID)
)
