CREATE TABLE [silver.NCCM].PARTICIPANTS_BRIDGE (
    [PARTICIPANTS_BRIDGE_ID] INT IDENTITY(1, 1) NOT NULL,

    [CONTACT_DIM_ID] INT NOT NULL,
    [PROGRAM_ENGAGEMENT_DIM_ID] INT NOT NULL,

    [ROW_CALENDAR_DATE] DATE NOT NULL,
    [ROW_CREATED_AT] DATETIME NULL,
    [ROW_UPDATED_AT] DATETIME NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,

    CONSTRAINT [PK_PARTICIPANTS_BRIDGE] PRIMARY KEY ([PARTICIPANTS_BRIDGE_ID]),
    CONSTRAINT [UQ_PARTICIPANTS_BRIDGE] UNIQUE([CONTACT_DIM_ID], [PROGRAM_ENGAGEMENT_DIM_ID])
)
