CREATE TABLE [silver.NCCM].RESP_ASSES_HISTORY (
    [CLIENT] VARCHAR(18) NOT NULL,
    [UQ_KEY_HASH] BINARY(16) NOT NULL,
    [FUNDING_PROGRAM] VARCHAR(255) NULL,
    [REFERRAL_STATUS_CODE] VARCHAR(255) NULL,
    [REGION] VARCHAR(255) NULL,
    [CLIENT_COMMENCEMENT_DATE] DATE NULL,
    [ROW_IS_CURRENT] BIT NOT NULL,
    [ROW_IS_CURRENT_FOR_THE_DAY] BIT NOT NULL,
    [ROW_EFFECTIVE_DATE_TIME] DATETIME NOT NULL,
    [ROW_CALENDAR_DATE] DATE NOT NULL,
    [ROW_END_DATE_TIME] DATETIME NULL,
    [ROW_REASON_FOR_CHANGE] NVARCHAR(1024) NULL,
    [ROW_HASH_SUM] BINARY(16) NOT NULL,
    CONSTRAINT [PK_RESP_ASSES_HISTORY] PRIMARY KEY (CLIENT, ROW_EFFECTIVE_DATE_TIME)
)