CREATE TABLE [bronze.NCCM].ACCOUNT (
    -- PK
    [ID] VARCHAR(18) NOT NULL,

    -- Attributes
    [EMPLOYER__C] NVARCHAR(2048) NULL,
    [ISDELETED] INT NOT NULL,

    -- Hash
    [ROW_HASH_SUM] VARCHAR(32) NOT NULL,

    -- Temporal
    [RowVersion] ROWVERSION NOT NULL,
    [ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo]),

    CONSTRAINT PK_ACCOUNT PRIMARY KEY CLUSTERED ([Id])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [bronze.NCCM].ACCOUNT_HISTORY));
