CREATE TABLE [bronze.NCCM].PLACEMENT (
    -- PK
    [ID] VARCHAR(18) NOT NULL,

    -- Attributes
    [ANCHOR_DATE__C] DATE NULL,
    [CONTACT__C] VARCHAR(255) NULL,
    [END_DATE__C] DATE NULL,
    [INTERVIEW_DATE__C] DATE NULL,
    [PLACED_DATE__C] DATE NULL,
    [PLACEMENT_TYPE__C] VARCHAR(255) NULL,
    [REFERRED_TO_EMPLOYER_DATE__C] DATE NULL,
    [START_DATE__C] DATE NULL,
    [STATUS__C] VARCHAR(255) NULL,
    [VACANCY_ID__C] VARCHAR(255) NULL,
    [ISDELETED] INT NOT NULL,

    -- Hash
    [ROW_HASH_SUM] VARCHAR(32) NOT NULL,

    -- Temporal
    [RowVersion] ROWVERSION NOT NULL,
    [ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo]),

    CONSTRAINT PK_PLACEMENT PRIMARY KEY CLUSTERED ([Id])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [bronze.NCCM].PLACEMENT_HISTORY));
