CREATE TABLE [raw.FNC].[Gldetail_PROD](
	[Recordno] [nvarchar](255) NOT NULL,
	[Batchkey] [bigint] NULL,
	[Batch_date] [date] NULL,
	[Batch_title] [nvarchar](2000) NULL,
	[Symbol] [nvarchar](255) NULL,
	[Batch_no] [bigint] NULL,
	[Bookid] [nvarchar](2000) NULL,
	[Childentity] [nvarchar](2000) NULL,
	[Modified] [datetime2](7) NULL,
	[Referenceno] [nvarchar](2000) NULL,
	[Adj] [bit] NULL,
	[Modulekey] [nvarchar](255) NULL,
	[Ownershipkey] [bigint] NULL,
	[Line_no] [bigint] NULL,
	[Entry_date] [date] NULL,
	[Tr_type] [bigint] NULL,
	[Document] [nvarchar](2000) NULL,
	[Accountno] [nvarchar](2000) NULL,
	[Accounttitle] [nvarchar](2000) NULL,
	[Statistical] [nvarchar](2000) NULL,
	[Departmentid] [nvarchar](2000) NULL,
	[Departmenttitle] [nvarchar](2000) NULL,
	[Locationid] [nvarchar](2000) NULL,
	[Locationname] [nvarchar](2000) NULL,
	[Currency] [nvarchar](255) NULL,
	[Basecurr] [nvarchar](255) NULL,
	[Description] [nvarchar](2000) NULL,
	[Debitamount] [decimal](28, 6) NULL,
	[Creditamount] [decimal](28, 6) NULL,
	[Amount] [decimal](28, 6) NULL,
	[Trx_debitamount] [decimal](28, 6) NULL,
	[Trx_creditamount] [decimal](28, 6) NULL,
	[Trx_amount] [decimal](28, 6) NULL,
	[Cleared] [nvarchar](2000) NULL,
	[Clrdate] [date] NULL,
	[Custentity] [nvarchar](2000) NULL,
	[Vendentity] [nvarchar](2000) NULL,
	[Empentity] [nvarchar](2000) NULL,
	[Locentity] [nvarchar](2000) NULL,
	[Recordtype] [nvarchar](255) NULL,
	[Recordid] [nvarchar](2000) NULL,
	[Docnumber] [nvarchar](2000) NULL,
	[State] [nvarchar](2000) NULL,
	[Whencreated] [date] NULL,
	[Whendue] [date] NULL,
	[Whenpaid] [date] NULL,
	[Whenmodified] [datetime2](7) NULL,
	[Prdescription] [nvarchar](2000) NULL,
	[Prcleared] [nvarchar](2000) NULL,
	[Prclrdate] [date] NULL,
	[Financialentity] [nvarchar](2000) NULL,
	[Totalentered] [decimal](28, 6) NULL,
	[Totalpaid] [decimal](28, 6) NULL,
	[Totaldue] [decimal](28, 6) NULL,
	[Entrydescription] [nvarchar](2000) NULL,
	[Glentrykey] [bigint] NULL,
	[Createdby] [nvarchar](2000) NULL,
	[Batch_state] [nvarchar](2000) NULL,
	[Entry_state] [nvarchar](2000) NULL,
	[Auwhencreated] [datetime2](7) NULL,
	[Aucreatedby] [bigint] NULL,
	[Modifiedby] [bigint] NULL,
	[Classdimkey] [bigint] NULL,
	[Classid] [nvarchar](255) NULL,
	[Classname] [nvarchar](255) NULL,
	[Customerdimkey] [bigint] NULL,
	[Customerid] [nvarchar](255) NULL,
	[Customername] [nvarchar](255) NULL,
	[Vendordimkey] [bigint] NULL,
	[Vendorid] [nvarchar](255) NULL,
	[Vendorname] [nvarchar](255) NULL,
	[Employeedimkey] [bigint] NULL,
	[Employeeid] [nvarchar](255) NULL,
	[Employeename] [nvarchar](255) NULL,
	[Itemdimkey] [bigint] NULL,
	[Itemid] [nvarchar](255) NULL,
	[Itemname] [nvarchar](255) NULL,
	[Projectdimkey] [bigint] NULL,
	[Projectid] [nvarchar](255) NULL,
	[Projectname] [nvarchar](255) NULL,
	[Record_url] [nvarchar](2000) NULL,
	[Gldimpurchase_type] [nvarchar](2000) NULL
);