CREATE TABLE [silver.FNC].TRANSACTION_FACT (
    [TRANSACTION_FACT_ID] INT NOT NULL,
    [ROW_HASH_SUM] BINARY(16) NOT NULL,

    [ARCHIVAL] BIT NOT NULL CONSTRAINT DF_TRANSACTION_FACT_ARCHIVAL DEFAULT(0),

    -- nullable
    [ACCOUNT_NUMBER] NVARCHAR(4000) NULL,
    [TOTAL_TITLE] NVARCHAR(255) NULL,
    [MEMBER_TYPE] NVARCHAR(2000) NULL,
    [RECORD_NUMBER] NVARCHAR(255) NULL,
    [GLACCTGRP_TITLE] NVARCHAR(255) NULL,

    -- not nullable
    [IS_DELETED] INT NOT NULL,

    [ROW_CREATED_AT] DATETIME NOT NULL,
    [ROW_UPDATED_AT] DATETIME NOT NULL,
    [ROW_VERSION] ROWVERSION NOT NULL,

    [VALID_FROM] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    [VALID_TO] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME ([VALID_FROM], [VALID_TO]),

    CONSTRAINT [PK_TRANSACTION_FACT] PRIMARY KEY (TRANSACTION_FACT_ID)
);