CREATE TABLE [logging.NCCM].EXECUTION_LOG (
    [Id] INT IDENTITY(1, 1) NOT NULL,
    [RunId] UNIQUEIDENTIFIER NOT NULL,
    [StepName] NVARCHAR(1024) NOT NULL,
    [StepNum] INT NOT NULL,
    [StartedAtUTC] DATETIME NOT NULL,
    [EndedAtUTC] DATETIME NULL,
    [Message] NVARCHAR(MAX) NULL,
    [ErrorMessage] NVARCHAR(MAX) NULL,
    [CreatedAtUTC] DATETIME CONSTRAINT DF_EXECUTION_LOG_CreatedAtUTC DEFAULT(GETUTCDATE()) NOT NULL,
    [UpdatedAtUTC] DATETIME CONSTRAINT DF_EXECUTION_LOG_UpdatedAtUTC DEFAULT(GETUTCDATE()) NOT NULL,
    CONSTRAINT PK_EXECUTION_LOG PRIMARY KEY ([Id])
)